spring:
  kafka:
    bootstrap-servers: 192.168.161.199:9021
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      #group-id: myGroup
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
